org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
# 阿里云 Maven 镜像在经代理访问时会触发 TLS 证书校验失败，这里让它直连。
systemProp.http.nonProxyHosts=maven.aliyun.com
