name: easylink_flutter
description: Wi-Fi Settings to MXCHIP/MXOS-based IoT hardware
version: 0.10.0
homepage: https://github.com/kagurazakayashi/EasylinkFlutter

environment:
  sdk: ^3.13.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  plugin:
    platforms:
      android:
        package: moe.yashi.easylink_flutter
        pluginClass: EasylinkFlutterPlugin
      ios:
        pluginClass: EasylinkFlutterPlugin
